/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_linjk_jniBridge_OpenCVUtils */

#ifndef _Included_cn_linjk_jniBridge_OpenCVUtils
#define _Included_cn_linjk_jniBridge_OpenCVUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_linjk_jniBridge_OpenCVUtils
 * Method:    img2gray
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_linjk_jniBridge_OpenCVUtils_img2gray
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
